<?php 
/**
 * @author		Sashas
 * @category    Sashas
 * @package     Sashas_Extensions
 * @copyright   Copyright (c) 2016 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<div class="col3-set">
	<div class="col-1">
		<div class="step-title">             
            <h2><?php  echo $this->__('Billing Information');?></h2>           
        </div>
        <div class="step1-content">
        	<?php echo $this->getChildHtml('billing');?>
        </div>
	</div>

	<div class="col-2">
		<div class="step-title">             
            <h2><?php  echo $this->__('Payment Information');?></h2>           
        </div>	
        <div class="step2-content">
        	<?php echo $this->getChildHtml('payment');?>
        </div>        
	</div>
	
	<div class="col-3">
		<div class="step-title">             
            <h2><?php  echo $this->__('Order Review');?></h2>           
        </div>
        <div class="step3-content">
        	<?php echo $this->getChildHtml('review');?>
        </div>        	
	</div>	
</div>


<script type="text/javascript">

var ajax_load_html='<div class="please-wait">';
	ajax_load_html+='<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper("core")->quoteEscape($this->__("Loading...")) ?>" title="<?php echo Mage::helper("core")->quoteEscape($this->__("Loading...")) ?>" class="v-middle" />';
	ajax_load_html+='<?php echo $this->__('Loading...') ?></div>';
  
  
  
function refreshAddress(){
    
    var billingUrl='<?php echo $this->getBillingAction() ?>';   
    jQuery('.step1-content').html(ajax_load_html);
    
    jQuery.ajax({
  	  method: "POST",
  	  url: billingUrl  	 
  	}).done(function( response ) {
  		  jQuery('.step1-content').html(response.content);   		 
  	  });  
}

function refreshPayment(){
    
    var paymentUrl='<?php echo $this->getPaymentAction() ?>';   
    jQuery('.step2-content').html(ajax_load_html);
    
    jQuery.ajax({
  	  method: "POST",
  	  url: paymentUrl  	 
  	}).done(function( response ) {
  		  jQuery('.step2-content').html(response.content);   		 
  	  });  
}

function refreshReview(){
    
    var reviewUrl='<?php echo $this->getReviewAction() ?>';   
    jQuery('.step3-content').html(ajax_load_html);
    
    jQuery.ajax({
  	  method: "POST",
  	  url: reviewUrl  	 
  	}).done(function( response ) {
  		  jQuery('.step3-content').html(response.content);   		 
  	  });  
}


function saveOrder(){
    
    var saveUrl='<?php echo $this->getUrl('checkout/onestep/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>';       
    jQuery('#review-buttons-container').prepend(ajax_load_html);
    jQuery('.btn-checkout').attr('disabled', true);
    jQuery.ajax({
  	  method: "POST",
  	  url: saveUrl,
  	  data: jQuery('#co-payment-form, #co-billing-form').serialize(), 
  	}).done(function( response ) {  		 
  	  		if (response.success==true){
    	  	  if (response.redirect) {
    	  	     location.href = response.redirect;
    	  	     return true;
    	  	  }
  	  		} else if (response.error==true) {
  	  	  		alert(response.error_messages);
  	  		} else if (response.success==false && response.error==false) {
  	            if (response.update_section) {
  	                $('checkout-'+response.update_section.name+'-load').update(response.update_section.html);
  	            }
    	          jQuery('#review-buttons-container .please-wait').remove();		
    	          return true;
  	  		}else if (response.error==false){
  	  	  		alert('<?php echo $this->__('There was an error processing your order. Please contact us or try again later.');?>');
  	  		}
  	  	 jQuery('#review-buttons-container .please-wait').remove();		
 		 jQuery('.btn-checkout').attr('disabled', false);	 
  	  });  
}

function newBillingAddress(isNew){ 
	var selectElement = $('billing-address-select')
     
	 if (isNew) {
		 if (selectElement) {
		        selectElement.value='';
		 }
		 jQuery('#billing-new-address-form').show();
	 } else {
		 jQuery('#billing-new-address-form').hide();
	 }    
}

jQuery( document ).ready(function() {	
	jQuery( "input[name='payment[method]']" ).change(function() {
		 var updateUrl='<?php echo $this->getUrl('checkout/onestep/updatePaypalAjax', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>';       
		 jQuery('.step2-content').append(ajax_load_html);
		 jQuery('#co-payment-form').hide();
		 jQuery('.step3-content').html(ajax_load_html);
		 jQuery.ajax({
		  	  method: "POST",
		  	  url: updateUrl,
		  	  data: jQuery('#co-payment-form, #co-billing-form').serialize(), 
		  	}).done(function( response ) {  		 
		  	  		if (response.success==true){
		    	  	   jQuery('.paypal_info').html(response.paypal_html);
			    	   jQuery('.step3-content').html(response.review_html);
		  	  		} else {
		  	  	  		alert(response.error_messages);
		  	  		} 
		  	  	 jQuery('.step2-content .please-wait').remove();		
			  	 jQuery('#co-payment-form').show();
		  	  });  
	});
});

</script>