<?php 
/**
 * @author		Sashas
 * @category    Sashas
 * @package     Sashas_Extensions
 * @copyright   Copyright (c) 2016 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
 
<a class="login_popup hidden" href="#login_popup">Inline</a>
 
<div id="login_popup" class="inline hidden">
	<div class="col1-set">
	        <div class="col-1">
	        <h3><?php echo $this->__('Login') ?></h3>				        
	        <form id="login-form" method="post">
	        <fieldset>
	            <?php echo $this->getBlockHtml('formkey'); ?>
	            <h4><?php echo $this->__('Already registered?') ?> <?php echo $this->__('Please log in below:') ?></h4>
	            
	            <ul class="form-list">
	                <li>
	                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                    <div class="input-box">
	                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
	                    </div>
	                </li>
	                <li class='password-field'>
	                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
	                    <div class="input-box">
	                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
	                    </div>
	                </li>	                 
	            </ul>
	        </fieldset>
	        </form>
	    </div>
	</div>
	<div class="col1-set">
	    <div class="col-1">
	        <div class="buttons-set">
	            <p class="required">&nbsp;</p>
	            <button type="button" class="button modal-register-button" onclick="register();"><span><span><?php echo $this->__('Continue'); ?></span></span></button>
	         
	             	            
	            <button type="submit" class="button modal-login-button" onclick="onepstepLogin()"><span><span><?php echo $this->__('Login and Continue') ?></span></span></button>
	        </div>
		    <div class="please-wait" id="login-please-wait" style="display:none;">
		        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
		    </div>	        
	    </div>
	    <div class="forgot-password">
	    	<a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
	    	<p class="required"><?php echo $this->__('* Required Fields') ?></p>
	    </div>
	      
	</div>	
	
	 
</div>
<script type="text/javascript">
jQuery(document).ready(function() {
	jQuery(".login_popup").fancybox({
		maxWidth	: 350,
		maxHeight	: 400,
		fitToView	: false,	 
		autoSize	: false,
		closeClick	: false,
		openEffect	: 'none',
		closeEffect	: 'none'
	});
	<?php if (!$this->isCustomerLoggedIn()):?>
	jQuery(".login_popup").click();
	<?php endif;?>
});

//<![CDATA[
var loginForm = new VarienForm('login-form', true);
$('login-email').observe('keypress', bindLoginPost);
$('login-password').observe('keypress', bindLoginPost);
function bindLoginPost(evt){
    if (evt.keyCode == Event.KEY_RETURN) {
    	onepstepLogin();
    }
}
function onepstepLogin()
{
    if(loginForm.validator && loginForm.validator.validate()){

        jQuery('#advice-login-error').remove();
        jQuery('.modal-login-button').attr('disabled', true);
        jQuery('.modal-register-button').attr('disabled', true);
        jQuery('#login-please-wait').show();
        var formData=jQuery('#login-form').serialize();
        var loginUrl='<?php echo $this->getPostAction() ?>';
         
        jQuery.ajax({
      	  method: "POST",
      	  url: loginUrl,
      	  data: formData
      	}).done(function( response ) {
      		jQuery('#login-please-wait').hide();
          	if (response.status==1) {
				refreshAddress();
              	jQuery.fancybox.close();
          	} else {
          		var errorText=response.message;
          		jQuery('.password-field').append('<div  id="advice-login-error" class="validation-advice">'+errorText+'</div>');
          	}
      	   
        	jQuery('.modal-login-button').attr('disabled', false);
            jQuery('.modal-register-button').attr('disabled', false);
      	  });     
    }
}

function register()
{
	jQuery.fancybox.close();
}
//]]>
</script>