<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xml:lang="<?php echo $this->getLang() ?>"
	lang="<?php echo $this->getLang() ?>">
<head>
	<?php echo $this->getChildHtml('head')?>
</head>
<body
	<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
	<header> <nav
		class="navbar main-navigation-header navbar-fixed-top sticky-navbar">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->

		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target="#header-navigation">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a href="http://www.thematicwebs.com/demo/wp/eventix/layout1"
				class="navbar-brand logo"> <img
				src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/logo.png"
				alt="" style="height: 32px !important; width: 157px !important;"> <img
					src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/logo-dark.png"
					class="dark-logo-img" alt=""
					style="height: 32px ! important; width: 157px ! important; display: block;"></a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="header-navigation">
			<ul class="nav navbar-nav main-navigation navbar-right">
				<li class="current"><a href="#sec_23"> What </a></li>
				<li class=""><a href="#sec_41"> When </a></li>
				<li class=""><a href="#sec_29"> Who </a></li>
				<li class=""><a href="#sec_43"> How </a></li>
				<li><a href="#sec_49"> Where </a></li>
				<li><a
					href="http://www.thematicwebs.com/demo/wp/eventix/layout1/?page_id=19">
						Blog </a></li>


			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid --> </nav> </header>
	<!-- Navigation -->


	<section
		style="background-image: url(&quot;http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-content/uploads/2015/07/main-bg.jpg&quot;); background-size: 100% auto; background-position: 50% -400px;"
		id="main-section" class="parallax-scroll1">

	<div class="overlay"></div>

	<div class="container">
		<div class="row">
			<div class="col-md-3 hidden-sm visible-lg visible-md side-text">
				<p class="small-text">September 22th, 2013</p>
			</div>

			<div class="main-intro col-md-6 ">

				<p style="position: relative; visibility: visible; height: 70.8px;"
					class="curved-text">
					<span
						style="position: absolute; left: 50%; margin-left: -0.575em; transform: rotate(-34.1443deg); transform-origin: center 5em 0px;"
						class="char1">W</span><span
						style="position: absolute; left: 50%; margin-left: -0.3875em; transform: rotate(-21.3194deg); transform-origin: center 5em 0px;"
						class="char2">E</span><span
						style="position: absolute; left: 50%; margin-left: -0.35em; transform: rotate(-11.4925deg); transform-origin: center 5em 0px;"
						class="char3">L</span><span
						style="position: absolute; left: 50%; margin-left: -0.425em; transform: rotate(-1.1659deg); transform-origin: center 5em 0px;"
						class="char4">C</span><span
						style="position: absolute; left: 50%; margin-left: -0.475em; transform: rotate(10.8262deg); transform-origin: center 5em 0px;"
						class="char5">O</span><span
						style="position: absolute; left: 50%; margin-left: -0.5375em; transform: rotate(24.3174deg); transform-origin: center 5em 0px;"
						class="char6">M</span><span
						style="position: absolute; left: 50%; margin-left: -0.3875em; transform: rotate(36.6427deg); transform-origin: center 5em 0px;"
						class="char7">E</span>
				</p>

				<span class="medium-text">to the awesome</span>

				<h1>internet</h1>

				<span class="medium-text">Conference</span> <a href="#"
					class="main-button gradient"> Register Here </a>

			</div>

			<div class="col-md-3 hidden-sm visible-lg visible-md side-text">
				<p class="small-text pull-right">Standard pass: 20$</p>
			</div>

		</div>
	</div>
	</section>




	<section id="sec_23"
		style="padding:0px !important; margin:0px !important;">

	<h2 style="display: none">empty</h2>

	<section class=" general-row">
	<div class="wpb_column ">
		<section id="about-section"> <span class="section-title">What is all
			that about?</span>
		<h2>the Massive event</h2>
		<div class="container">
			<div class="row">
				<div class="col-md-4 text-left left-wrapper">
					<p class="large-text">Maecenas nec fermentum tellus porttitor
						sagittis lorem ipsum dolor nulla pretium neq congue sapien</p>
				</div>
				<div class="col-md-4 text-center rounded_image">
					<a href="https://vimeo.com/110802348" class="video-link"> <img
						style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: bounceIn;"
						src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/video.png"
						class="wow bounceIn img-responsive animated"
						data-wow-duration="1s" data-wow-offset="10" data-wow-delay=".3s"
						alt=""></a>
				</div>
				<div class="col-md-4 text-left right-wrapper">
					<h3>Lorem ipsum set</h3>
					<p class="medium-text">Vestibulum ante ipsum primis faucibus luctus
						et ultrices posuere cubilia curae sollicitudin augue.</p>
					<br>
						<h3>Castel ector simerd</h3>
						<p class="medium-text">Scelerisque mi rutrum vel nunc porta felis
							id ligula mattis ac aliquet arcu varius quis que porta.</p>
				
				</div>
			</div>
		</div>
		</section>

	</div>

	<div class="clearfix"></div>
	</section> <section class=" general-row">
	<div class="wpb_column ">
		<section
			style="background: transparent url(&quot;http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-content/uploads/2015/07/feature-bg.png&quot;) no-repeat fixed 50% 37px;"
			id="features" class="parallax-scroll2 no_color">
		<div class="container">

			<span class="section-title">Some features</span>
			<h2>More Details</h2>
			<div style="opacity: 1; display: block;" id="features-slider"
				class="owl-carousel owl-theme">
				<div class="owl-wrapper-outer">
					<div
						style="width: 4560px; left: 0px; display: block; transition: all 0ms ease 0s; transform: translate3d(0px, 0px, 0px);"
						class="owl-wrapper">
						<div style="width: 380px;" class="owl-item">
							<div
								style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
								class="feature-item wow fadeIn animated" data-wow-duration="1s"
								data-wow-delay=".3s">
								<i class="fa fa-star"></i>
								<h3>SEO Optimized</h3>
								<p>Cras eu lacus sed quam scelerisque vene natis phasellusenim
									ipsum.</p>
								<a href="#"> Read More </a>
							</div>
						</div>
						<div style="width: 380px;" class="owl-item">
							<div
								style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
								class="feature-item wow fadeIn animated" data-wow-duration="1s"
								data-wow-delay=".3s">
								<i class="fa fa-camera-retro"></i>
								<h3>Responsive Layout</h3>
								<p>Cras eu lacus sed quam scelerisque vene natis phasellusenim
									ipsum.</p>
								<a href="#"> Read More </a>
							</div>
						</div>
						<div style="width: 380px;" class="owl-item">
							<div
								style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
								class="feature-item wow fadeIn animated" data-wow-duration="1s"
								data-wow-delay=".3s">
								<i class="fa fa-microphone"></i>
								<h3>Clean Design</h3>
								<p>Cras eu lacus sed quam scelerisque vene natis phasellusenim
									ipsum.</p>
								<a href="#"> Read More </a>
							</div>
						</div>
						<div style="width: 380px;" class="owl-item">
							<div
								style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
								class="feature-item wow fadeIn animated" data-wow-duration="1s"
								data-wow-delay=".3s">
								<i class="fa fa-star"></i>
								<h3>SEO Optimized</h3>
								<p>Cras eu lacus sed quam scelerisque vene natis phasellusenim
									ipsum.</p>
								<a href="#"> Read More </a>
							</div>
						</div>
						<div style="width: 380px;" class="owl-item">
							<div
								style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
								class="feature-item wow fadeIn animated" data-wow-duration="1s"
								data-wow-delay=".3s">
								<i class="fa fa-camera-retro"></i>
								<h3>Responsive Layout</h3>
								<p>Cras eu lacus sed quam scelerisque vene natis phasellusenim
									ipsum.</p>
								<a href="#"> Read More </a>
							</div>
						</div>
						<div style="width: 380px;" class="owl-item">
							<div
								style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
								class="feature-item wow fadeIn animated" data-wow-duration="1s"
								data-wow-delay=".3s">
								<i class="fa fa-microphone"></i>
								<h3>Clean Design</h3>
								<p>Cras eu lacus sed quam scelerisque vene natis phasellusenim
									ipsum.</p>
								<a href="#"> Read More </a>
							</div>
						</div>
					</div>
				</div>





				<div class="owl-controls">
					<div class="owl-pagination">
						<div class="owl-page active">
							<span class=""></span>
						</div>
						<div class="owl-page">
							<span class=""></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		</section>

	</div>

	<div class="clearfix"></div>
	</section> </section>


	<section id="sec_41"
		style="padding:0px !important; margin:0px !important;">

	<h2 style="display: none">empty</h2>

	<section class=" general-row">
	<div class="wpb_column ">
		<section id="z-layout1">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-5">
					<span class="section-title">When</span>
					<h2>Are You Ready to have fun?</h2>
					<hr>
						<p>Lorem ipsum dolor sit amet, consec tetur lil adipiscing elit
							proin at iaculis enim donec vitae orci justo aliquam vel con
							sequat odio euismod urna sit amet.</p>
						<a href="#" class="button">sponsor us</a>
				
				</div>
				<div
					class="col-lg-7 col-md-7 col-lg-offset-1 text-center event_single event_single_image">
					<input id="cal_width1" value="700" type="hidden">
						<div id="bigcalendar1">
							<style type="text/css">
#bigcalendar1 table {
	border-collapse: inherit !important;
}

#TB_window {
	z-index: 10000;
}

#bigcalendar1 .calyear_table td {
	vertical-align: middle !important;
}

#bigcalendar1 table {
	border-collapse: initial;
	border: 0px;
	max-width: none;
}

#bigcalendar1 table td {
	padding: 0px;
	vertical-align: none;
	border-top: none;
	line-height: none;
	text-align: none;
}

#bigcalendar1 p,ol,ul,dl,address {
	margin-bottom: 0;
}

#bigcalendar1 td,#bigcalendar1 tr,#spiderCalendarTitlesList td,#spiderCalendarTitlesList tr
	{
	border: none;
}

#bigcalendar1 .general_table {
	border-radius: 0px;
}

#bigcalendar1 .top_table {
	border-top-left-radius: 0px;
	border-top-right-radius: 0px;
}

#bigcalendar1 .general_table table tr:last-child>td:first-child {
	border-bottom-left-radius: 0px;
}

#bigcalendar1 .general_table table tr:last-child>td:last-child {
	border-bottom-right-radius: 0px;
}

#bigcalendar1 .cala_arrow a:link,#bigcalendar1 .cala_arrow a:visited {
	text-decoration: none;
	background: none;
	font-size: 50px;
}

#bigcalendar1 .cala_arrow a:hover {
	text-decoration: none;
	background: none;
}

#bigcalendar1 .cala_day a:link,#bigcalendar1 .cala_day a:visited {
	text-decoration: none;
	background: none;
	font-size: 12px;
	color: red;
}

#bigcalendar1 .cala_day a:hover {
	text-decoration: none;
	background: none;
}

#bigcalendar1 .cala_day {
	border: 1px solid #A9A9A9 !important;
	vertical-align: top;
}

#bigcalendar1 .weekdays {
	border: 1px solid #A9A9A9 !important;
	vertical-align: middle;
}

#bigcalendar1 .week_days {
	font-size: 25px;
}

#bigcalendar1 .calyear_table {
	border-spacing: 0;
	width: 100%;
}

#bigcalendar1 .calmonth_table {
	border-spacing: 0;
	width: 100%;
}

#bigcalendar1 .calbg,#bigcalendar1 .calbg td {
	text-align: center;
	width: 14%;
}

#bigcalendar1 .caltext_color_other_months {
	color: #B0B0B0;
	border: 1px solid #A9A9A9 !important;
	vertical-align: top;
}

#bigcalendar1 .caltext_color_this_month_unevented {
	color: #6A6A6A;
}

#bigcalendar1 .calfont_year {
	font-size: 24px;
	font-weight: bold;
	color: #F9F2F4;
}

#bigcalendar1 .calsun_days {
	color: #6A6A6A;
	border: 1px solid #A9A9A9 !important;
	vertical-align: top;
	text-align: left;
	background-color: #E1E1E1;
}

#bigcalendar1 .views {
	float: right;
	background-color: #01799C;
	min-height: 25px;
	min-width: 70px;
	margin-right: 2px;
	text-align: center;
	cursor: pointer;
	position: relative;
	top: 5px;
}

#bigcalendar1 .views span {
	padding: 7px;
}

#bigcalendar1 .views_select,#bigcalendar1 #views_select {
	background-color: #01799C;
	width: 120px;
	text-align: center;
	cursor: pointer;
	padding: 6px;
	position: relative;
}

#bigcalendar1 #views_select {
	min-height: 30px;
}

#drop_down_views {
	list-style-type: none !important;
	display: none;
	z-index: 4545;
}

#drop_down_views>li:hover .views_select,#drop_down_views>li.active .views_select
	{
	background: #005478;
}

#drop_down_views>li {
	border-bottom: 1px solid #fff !important;
}

#views_tabs_select {
	display: none;
}

#cal_event p {
	color: #236283
}
</style>

							<div id="afterbig1" style="width: 102.48901903367495%;">
								<div style="width: 100%;">
									<table style="width: 100%;" cellpadding="0" cellspacing="0">
										<tbody>
											<tr>
												<td>
													<div id="views_tabs" style="width: 100.3%;">
														<div class="views" style=""
															onclick="showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_day&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2015-09-29&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0&amp;rand=1','1','0')">
															<span style="color: #FFFFFF; font-size: 13px">Day</span>
														</div>
														<div class="views" style=""
															onclick="showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_week&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;months=08,09,10&amp;date=2015-09-29&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0&amp;rand=1','1','0')">
															<span style="color: #FFFFFF; font-size: 13px">Week</span>
														</div>
														<div class="views" style=""
															onclick="showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_list&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2015-09&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0&amp;rand=1','1','0')">
															<span style="color: #FFFFFF; font-size: 13px">List</span>
														</div>
														<div class="views"
															style="background-color: #005478; top: 0;"
															onclick="showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_month&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2015-09&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0&amp;rand=1','1','0')">
															<span style="color: #FFFFFF; font-size: 13px">Month</span>
														</div>
													</div>

													<div id="views_tabs_select" style="display: none">
														<div id="views_select"
															style="background-color: #005478; color: #FFFFFF; font-size: 13px">
															Month<span>►</span>
														</div>
														<ul id="drop_down_views"
															style="float: left; top: inherit; left: -20px; margin-top: 0px;">
															<li style="">
																<div class="views_select"
																	onclick="showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_day&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2015-09-29&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0','1','0')">
																	<span
																		style="position: relative; top: 25%; color: #FFFFFF; font-size: 13px">Day</span>
																</div>
															</li>

															<li style=""><div class="views_select"
																	onclick="showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_week&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;months=08,09,10&amp;date=2015-09-29&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0','1','0')">
																	<span
																		style="position: relative; top: 25%; color: #FFFFFF; font-size: 13px">Week</span>
																</div></li>

															<li style=""><div class="views_select"
																	onclick="showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_list&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2015-09&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0','1','0')">
																	<span
																		style="position: relative; top: 25%; color: #FFFFFF; font-size: 13px">List</span>
																</div></li>

															<li class="active" style=""><div class="views_select"
																	onclick="showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_month&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2015-09&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0','1','0')">
																	<span
																		style="position: relative; top: 25%; color: #FFFFFF; font-size: 13px">Month</span>
																</div></li>

														</ul>
													</div>
												</td>
											</tr>
											<tr>
												<td>
													<table class="general_table"
														style="border-spacing: 0; width: 100%; border: #005478 solid 0px; margin: 0; padding: 0; background-color: #E1E1E1;"
														cellpadding="0" cellspacing="0">
														<tbody>
															<tr>
																<td style="padding: 0; margin: 0" width="100%">
																	<table
																		style="border-spacing: 0; font-size: 12px; margin: 0; padding: 0; width: 100%;"
																		border="0" cellpadding="0" cellspacing="0">
																		<tbody>
																			<tr style="height: 40px; width: 100%;">
																				<td class="top_table" colspan="7"
																					style="z-index: 5; position: relative; background-image: url('http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-content/plugins/spider-event-calendar/front_end/images/Stver.png'); padding: 0; margin: 0; background-color: #005478; height: 20px; background-repeat: no-repeat; background-size: 100% 100%;"
																					align="center">
																					<table class="calyear_table"
																						style="margin: 0; padding: 0; text-align: center; width: 100%; height: 100px;"
																						align="center" border="0" cellpadding="0"
																						cellspacing="0">
																						<tbody>
																							<tr>
																								<td width="15%">
																									<div
																										onclick="javascript:showbigcalendar('bigcalendar1','http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_month&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2014-09&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0','1','0')"
																										style="text-align: center; cursor: pointer; width: 100%; background-color: #000000; filter: alpha(opacity = 30); opacity: 0.3;">
																										<span style="font-size: 18px; color: #FFF">2014</span>
																									</div>
																								</td>
																								<td class="cala_arrow"
																									style="text-align: right; margin: 0px; padding: 0px"
																									width="15%"><a
																									style="text-shadow: 1px 1px 2px black; color: #CCD1D2;"
																									href="javascript:showbigcalendar('bigcalendar1','http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_month&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2015-08&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0','1','0')"><img
																										src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/25c0.png"
																										alt="◀" class="emoji" draggable="false"></a></td>
																								<td style="text-align: center; margin: 0;"
																									width="40%"><input name="month"
																									readonly="readonly" value="September"
																									type="hidden"> <span
																										style="line-height: 30px; font-family: arial; color: #F9F2F4; font-size: 25px; text-shadow: 1px 1px black;">2015,
																											September</span></td>
																								<td
																									style="margin: 0; padding: 0; text-align: left"
																									class="cala_arrow" width="15%"><a
																									style="text-shadow: 1px 1px 2px black; color: #CCD1D2"
																									href="javascript:showbigcalendar('bigcalendar1','http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_month&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2015-10&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0','1','0')"><img
																										src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/25b6.png"
																										alt="▶" class="emoji" draggable="false"></a></td>
																								<td width="15%">
																									<div
																										onclick="javascript:showbigcalendar('bigcalendar1','http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_month&amp;theme_id=13&amp;calendar=1&amp;select=month,list,week,day,&amp;date=2016-09&amp;many_sp_calendar=1&amp;cur_page_url=http://www.thematicwebs.com/demo/wp/eventix/layout1/&amp;cat_id&amp;widget=0','1','0')"
																										style="text-align: center; cursor: pointer; width: 100%; background-color: #000000; filter: alpha(opacity = 30); opacity: 0.3;">
																										<span style="font-size: 18px; color: #FFF">2016</span>
																									</div>
																								</td>
																							</tr>
																						</tbody>
																					</table>
																				</td>
																			</tr>
																			<tr style="background-color: #D6D6D6;" align="center"
																				height="50">
																				<td class="weekdays"
																					style="width: 14.2857143%; color: #005D78; margin: 0; padding: 0; background-color: #B5B5B5">
																					<div class="calbottom_border"
																						style="text-align: center; margin: 0; padding: 0;">
																						<b class="week_days">Su </b>
																					</div>
																				</td>
																				<td class="weekdays"
																					style="width: 14.2857143%; color: #005D78; margin: 0; padding: 0">
																					<div class="calbottom_border"
																						style="text-align: center; margin: 0; padding: 0;">
																						<b class="week_days">Mo </b>
																					</div>
																				</td>
																				<td class="weekdays"
																					style="width: 14.2857143%; color: #005D78; margin: 0; padding: 0">
																					<div class="calbottom_border"
																						style="text-align: center; margin: 0; padding: 0;">
																						<b class="week_days">Tu </b>
																					</div>
																				</td>
																				<td class="weekdays"
																					style="width: 14.2857143%; color: #005D78; margin: 0; padding: 0">
																					<div class="calbottom_border"
																						style="text-align: center; margin: 0; padding: 0;">
																						<b class="week_days">We </b>
																					</div>
																				</td>
																				<td class="weekdays"
																					style="width: 14.2857143%; color: #005D78; margin: 0; padding: 0">
																					<div class="calbottom_border"
																						style="text-align: center; margin: 0; padding: 0;">
																						<b class="week_days">Th </b>
																					</div>
																				</td>
																				<td class="weekdays"
																					style="width: 14.2857143%; color: #005D78; margin: 0; padding: 0">
																					<div class="calbottom_border"
																						style="text-align: center; margin: 0; padding: 0;">
																						<b class="week_days">Fr </b>
																					</div>
																				</td>
																				<td class="weekdays"
																					style="width: 14.2857143%; color: #005D78; margin: 0; padding: 0">
																					<div class="calbottom_border"
																						style="text-align: center; margin: 0; padding: 0;">
																						<b class="week_days">Sa </b>
																					</div>
																				</td>
																			</tr>
																			<tr id="days" style="line-height: 15px;" height="70">
																				<td class="caltext_color_other_months"
																					style="background-color: #E1E1E1"><span
																					style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">30</span>
																				</td>
																				<td class="caltext_color_other_months"
																					style="background-color: #E1E1E1"><span
																					style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">31</span>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">1</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">2</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">3</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">4</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">5</p>
																				</td>
																			</tr>
																			<tr style="line-height: 15px" height="70">
																				<td class="calsun_days"
																					style="padding: 0; margin: 0; line-height: 1.3; font-family: tahoma; padding-left: 5px; font-size: 25px">
																					<b>6</b>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">7</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">8</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">9</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">10</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">11</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">12</p>
																				</td>
																			</tr>
																			<tr style="line-height: 15px" height="70">
																				<td class="calsun_days"
																					style="padding: 0; margin: 0; line-height: 1.3; font-family: tahoma; padding-left: 5px; font-size: 25px">
																					<b>13</b>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">14</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">15</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">16</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">17</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">18</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">19</p>
																				</td>
																			</tr>
																			<tr style="line-height: 15px" height="70">
																				<td class="calsun_days"
																					style="padding: 0; margin: 0; line-height: 1.3; font-family: tahoma; padding-left: 5px; font-size: 25px">
																					<b>20</b>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">21</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">22</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">23</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">24</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">25</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">26</p>
																				</td>
																			</tr>
																			<tr style="line-height: 15px" height="70">
																				<td class="calsun_days"
																					style="padding: 0; margin: 0; line-height: 1.3; font-family: tahoma; padding-left: 5px; font-size: 25px">
																					<b>27</b>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">28</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 3px solid #005478 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">29</p>
																				</td>
																				<td
																					style="color: #6A6A6A; padding: 0; margin: 0; line-height: 15px; border: 1px solid #A9A9A9 !important; vertical-align: top;">
																					<p
																						style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px;">30</p>
																				</td>
																				<td class="caltext_color_other_months"
																					style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px; background-color: #E1E1E1;">1</td>
																				<td class="caltext_color_other_months"
																					style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px; background-color: #E1E1E1;">2</td>
																				<td class="caltext_color_other_months"
																					style="font-size: 25px; line-height: 1.3; font-family: tahoma; padding-left: 5px; background-color: #E1E1E1;">3</td>
																			</tr>
																		</tbody>
																	</table> <input value="1" name="day"
																	style="display: none" type="text">
																
																</td>
															</tr>
														</tbody>
													</table>
												</td>
											</tr>
										</tbody>
									</table>

									<script>
  
		   jQuery(document).ready(function (){
					  
			jQuery('#views_select').click(function () {
			jQuery('#drop_down_views').stop(true, true).delay(200).slideDown(500);
		  }, function () {
			jQuery('#drop_down_views').stop(true, true).slideUp(500);
		  });
		  if(jQuery(window).width() > 640 )
		  {
			jQuery('drop_down_views').hide();
		  }
	});
  </script>


									<style>
@media only screen and (max-width : 640px) {
	#views_tabs,#drop_down_views {
		display: none;
	}
	#views_tabs_select {
		display: block !important;
	}
}

@media only screen and (max-width : 968px) {
	#cats>li {
		float: none;
	}
}

.categories1,.categories2 {
	display: inline-block;
}

.categories2 {
	position: relative;
	left: -9px;
	cursor: pointer;
}

.categories2:first-letter {
	color: #fff;
}
</style>

									<style>
#cats #category {
	text-decoration: underline;
	cursor: pointer;
}
</style>
									<ul id="cats" style="list-style-type: none;"></ul>
									<br><br>
								
								</div>
							</div>
						</div> <script> 
    var tb_pathToImage = "http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-content/plugins/spider-event-calendar/images/loadingAnimation.gif";
    var tb_closeImage = "http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-content/plugins/spider-event-calendar/images/tb-close.png"
	var randi;
    if (typeof showbigcalendar != 'function') {
      function showbigcalendar(id, calendarlink, randi,widget) {
        var xmlHttp;
        try {
          xmlHttp = new XMLHttpRequest();// Firefox, Opera 8.0+, Safari
        }
        catch (e) {
          try {
            xmlHttp = new ActiveXObject("Msxml2.XMLHTTP"); // Internet Explorer
          }
          catch (e) {
            try {
              xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            catch (e) {
              alert("No AJAX!?");
              return false;
            }
          }
        }
        xmlHttp.onreadystatechange = function () {
          if (xmlHttp.readyState == 4) {
            jQuery('#' + id).html(xmlHttp.responseText);
          }
        }
        xmlHttp.open("GET", calendarlink, false);
        xmlHttp.send();
	 jQuery(document).ready(function (){
     jQuery('#views_select').toggle(function () {	
    jQuery('#drop_down_views').stop(true, true).delay(200).slideDown(500);
  }, function () { 
    jQuery('#drop_down_views').stop(true, true).slideUp(500);	
  });
	});
if(widget!=1)
{
  if(jQuery(window).width() > 640)
  {
	jQuery('drop_down_views').hide();
		var parent_width = document.getElementById('bigcalendar'+randi).parentNode.clientWidth;
		var calwidth=  document.getElementById('cal_width'+randi).value;
		var responsive_width = (calwidth)/parent_width*100;
		document.getElementById('afterbig'+randi).setAttribute('style','width:'+responsive_width+'%;');
		jQuery('pop_table').css('height','100%');
  }
 else if(jQuery(jQuery('#bigcalendar'+randi).parent()).width() > 640)
  {
	jQuery('drop_down_views').hide();
		var parent_width = document.getElementById('bigcalendar'+randi).parentNode.clientWidth;
		var calwidth=  document.getElementById('cal_width'+randi).value;
		var responsive_width = (calwidth)/parent_width*100;
		document.getElementById('afterbig'+randi).setAttribute('style','width:'+responsive_width+'%;');
		jQuery('pop_table').css('height','100%');
  } 
	else
	{
			document.getElementById('afterbig'+randi).setAttribute('style','width:100%;');	
	}
}
        var thickDims, tbWidth, tbHeight;
        jQuery(document).ready(function ($) {
          thickDims = function () {
			jQuery('#TB_window iframe').css('margin-left','0%');
			jQuery('#TB_window iframe').css('margin-top','0%');
			jQuery('#TB_window iframe').css('margin-left','0%');
			jQuery('#TB_window iframe').css('margin-top','0%');			
			jQuery('#TB_window iframe').css('padding-left','0%');
			jQuery('#TB_window iframe').css('padding-top','0%');		
             var tbWindow = $('#TB_window'), H = $(window).height(), W = $(window).width(), w, h;
            if (tbWidth) {
              if (tbWidth < (W - 90)) w = tbWidth; else  w = W - 200;
            } else w = W - 200;
            if (tbHeight) {
              if (tbHeight < (H - 90)) h = tbHeight; else  h = H - 200;
            } else h = H - 200;			
            if (tbWindow.size()) {
              tbWindow.width(w).height(h);
              $('#TB_iframeContent').width(w).height(h - 27);
              tbWindow.css({'margin-left':'-' + parseInt((w / 2), 10) + 'px'});
              if (typeof document.body.style.maxWidth != 'undefined')
                tbWindow.css({'top':(H - h) / 2, 'margin-top':'0'});
            }
			 if(jQuery(window).width() < 640 ){
			  var tb_left = parseInt((w / 2), 10) + 20;
				jQuery('#TB_window').css('left', tb_left + 'px')
				jQuery('#TB_window').css('width','90%');
				jQuery('#TB_window').css('margin-top','-13%');
				jQuery('#TB_window iframe').css('height','100%');
				jQuery('#TB_window iframe').css('width','100%');
			}
			   if(jQuery(window).width() > 640 )
			   {
					jQuery('#TB_window').css('left','50%');
				}
		if (typeof popup_width_from_src != "undefined") {
				popup_width_from_src=jQuery('.thickbox-previewbigcalendar'+randi).attr('href').indexOf('tbWidth=');
				str=jQuery('.thickbox-previewbigcalendar'+randi).attr('href').substr(popup_width_from_src+8,150)
				find_amp=str.indexOf('&');
				width_orig=str.substr(0,find_amp);				
				find_eq=str.indexOf('=');
				height_orig=str.substr(find_eq+1,5);
			jQuery('#TB_window').css('max-width',width_orig+'px');
			jQuery('#TB_window iframe').css('max-width',width_orig+'px');
			jQuery('#TB_window').css('max-height',height_orig+'px');
			}			
			jQuery('#TB_window').css('background','none');
			jQuery('#TB_window').css('background-color','none');
			jQuery('#TB_window iframe').css('background-color','none');			
          };
          thickDims();
          $(window).resize(function () {
            thickDims();
			if(jQuery(window).width() < 640 ){
				jQuery('#TB_window').css('width','90%');
				jQuery('#TB_window').css('margin-top','-13%');
				jQuery('#TB_window iframe').css('height','100%');
				jQuery('#TB_window').css('height','100%');
			}		
if(jQuery(window).width() > 900 )
			   {
					jQuery('#TB_window').css('left','50%');						
				}
		  });		  
          $('a.thickbox-preview' + id).click(function () {
            tb_click.call(this);
            var alink = jQuery(this).parents('.available-theme').find('.activatelink'), link = '', href = jQuery(this).attr('href'), url, text;
            var reg_with = new RegExp(xx_cal_xx + "tbWidth=[0-9]+");	
            if (tbWidth = href.match(reg_with))
              tbWidth = parseInt(tbWidth[0].replace(/[^0-9]+/g, ''), 10);
            else
              tbWidth = jQuery(window).width() - 90;
            var reg_heght = new RegExp(xx_cal_xx + "tbHeight=[0-9]+");
            if (tbHeight = href.match(reg_heght))
              tbHeight = parseInt(tbHeight[0].replace(/[^0-9]+/g, ''), 10);
            else
              tbHeight = jQuery(window).height() - 60;
            jQuery('#TB_title').css({'background-color':'#222', 'color':'#dfdfdf'});
            jQuery('#TB_closeAjaxWindow').css({'float':'left'});
            jQuery('#TB_ajaxWindowTitle').css({'float':'right'}).html(link);			
            jQuery('#TB_iframeContent').width('100%');
            thickDims();			
            return false;			
          });		  	
        });
      }
    }	
    document.onkeydown = function (evt) {
      evt = evt || window.event;
      if (evt.keyCode == 27) {
        document.getElementById('sbox-window').close();
      }
    };
     showbigcalendar('bigcalendar1', 'http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-admin/admin-ajax.php?action=spiderbigcalendar_month&theme_id=13&calendar=1&select=month,list,week,day,&date=2015-09&months&many_sp_calendar=1&cur_page_url=http%3A%2F%2Fwww.thematicwebs.com%2Fdemo%2Fwp%2Feventix%2Flayout1%2F&widget=0&rand=1','1','0');	  
  </script>
						<style>
#TB_iframeContent {
	height: 100% !important;
}

#TB_window {
	z-index: 1000000;
}
</style>
				
				</div>
			</div>
		</div>
		</section>

	</div>

	<div class="clearfix"></div>
	</section> </section>


	<section id="sec_29"
		style="padding:0px !important; margin:0px !important;">

	<h2 style="display: none">empty</h2>

	<section class=" general-row">
	<div class="wpb_column ">
		<section id="team-section" class="gradient color_set">
		<div class="container">

			<span class="section-title">Our Speakers</span>
			<h2>the wisdom source</h2>
			<hr>
				<p class="main-text center-block">Quisque cursus in augue eget
					faucibus suspendisse vel mattis libero aliquam ultricies magna nec
					nisi laoreet, sed cursus quam blandit duis.</p>

				<div class="owl-carousel owl-theme"
					style="opacity: 1; display: block;" id="team-slider">
					<div class="owl-wrapper-outer">
						<div
							style="width: 6840px; left: 0px; display: block; transition: all 0ms ease 0s; transform: translate3d(0px, 0px, 0px);"
							class="owl-wrapper">
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img3.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>James Winfield</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img2.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>William Doe</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img1.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>Jane Tarza</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img3.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>James Winfield</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img2.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>William Doe</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img1.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>Jane Tarzan</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img3.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>James Winfield</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img2.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>William Doe</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
							<div style="width: 380px;" class="owl-item">
								<div
									style="visibility: visible; animation-duration: 1s; animation-delay: 0.3s; animation-name: fadeIn;"
									class="team-item wow fadeIn animated" data-wow-duration="1s"
									data-wow-delay=".3s">
									<div class="wrapper center-block">
										<div class="team-thumbnail center-block gradient">

											<img
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/team-img1.png"
												alt="">

												<div class="hovered">
													<a href="#"> <i class="fa fa-twitter first"></i>
													</a> <a href="#"> <i class="fa fa-facebook second"></i>
													</a>
												</div>
										
										</div>
										<h3>Jane Tarzan</h3>
										<p>art director at Envato</p>
									</div>
								</div>
							</div>
						</div>
					</div>








					<div class="owl-controls">
						<div class="owl-pagination">
							<div class="owl-page active">
								<span class=""></span>
							</div>
							<div class="owl-page">
								<span class=""></span>
							</div>
							<div class="owl-page">
								<span class=""></span>
							</div>
						</div>
					</div>
				</div>
		
		</div>

		</section>

	</div>

	<div class="clearfix"></div>
	</section> <section class=" general-row">
	<div class="wpb_column ">
		<section
			style="background: transparent url(&quot;http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-content/uploads/2015/07/gallery-bg.jpg&quot;) no-repeat fixed 50% 471px;"
			id="z-layout2" class="parallax-scroll3">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-7 col-md-7 text-center">
					<ul class="owl-carousel owl-theme"
						style="opacity: 1; display: block;" id="gallery-slider">
						<div class="owl-wrapper-outer">
							<div
								style="width: 5224px; left: 0px; display: block; transition: all 0ms ease 0s; transform: translate3d(0px, 0px, 0px);"
								class="owl-wrapper">
								<div style="width: 653px;" class="owl-item">
									<li><img
										src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/gallery-img4.png"
										alt=""></li>
								</div>
								<div style="width: 653px;" class="owl-item">
									<li><img
										src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/gallery-img3.png"
										alt=""></li>
								</div>
								<div style="width: 653px;" class="owl-item">
									<li><img
										src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/gallery-img2.png"
										alt=""></li>
								</div>
								<div style="width: 653px;" class="owl-item">
									<li><img
										src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/gallery-img1.png"
										alt=""></li>
								</div>
							</div>
						</div>



						<div class="owl-controls">
							<div class="owl-buttons">
								<div class="owl-prev">
									<i class="fa fa-angle-left"></i>
								</div>
								<div class="owl-next">
									<i class="fa fa-angle-right"></i>
								</div>
							</div>
						</div>
					</ul>
				</div>
				<div class="col-lg-4 col-lg-offset-1 col-md-5">
					<span class="section-title">Gallery</span>
					<h2>in case you want to see it</h2>
					<hr>
						<p>Lorem ipsum dolor sit amet, consec tetur lil adipiscing elit
							proin at iaculis enim donec vitae orci justo aliquam vel con
							sequat odio euismod urna sit amet.</p>

						<a href="#" class="button">sponsor us</a>
				
				</div>

			</div>
		</div>
		</section>

	</div>

	<div class="clearfix"></div>
	</section> </section>


	<section id="sec_43"
		style="padding:0px !important; margin:0px !important;">

	<h2 style="display: none">empty</h2>

	<section class=" general-row">
	<div class="wpb_column ">
		<section id="timeline">
		<div class="container">

			<span class="section-title">Our Speakers</span>
			<h2>the wisdom source</h2>

			<div role="tabpanel">

				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
				</ul>
			</div>

			<div class="tab-content"></div>

			<a href="#" class="download-button center-block"> Download .pdf </a>

		</div>

		</section>

	</div>

	<div class="clearfix"></div>
	</section> <section class=" general-row">
	<div class="wpb_column ">
		<div class="hr_black">
			<div
				style="background: transparent url(&quot;http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-content/uploads/2015/07/gallery-bg.jpg&quot;) no-repeat fixed 50% 463px;"
				id="testimonials" class="parallax-scroll4 no_color">
				<div class="overlay no_color"></div>
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<ul class="owl-carousel owl-theme"
								style="opacity: 1; display: block;" id="testi-slider">
								<div class="owl-wrapper-outer">
									<div
										style="width: 6600px; left: 0px; display: block; transition: all 0ms ease 0s; transform: translate3d(0px, 0px, 0px);"
										class="owl-wrapper">
										<div style="width: 1100px;" class="owl-item">
											<li class="testi-slide testi_img"><a><img
													src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/testi-img.png"
													alt=""></a>
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
													Vivamus accumsan egestas neque in placerat sed dictum purus
													non sollicitudin consectetur. Quisque laoreet dolor nec est
													pellentesque, sed gravida ligula com modo suspendisse
													tempus sit amet nisi id aliquet.</p>
												<hr>
													<span> John Doer - <a href="#">Envato.com</a>

													</span></li>
										</div>
										<div style="width: 1100px;" class="owl-item">
											<li class="testi-slide testi_img"><a><img
													src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/testi-img.png"
													alt=""></a>
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
													Vivamus accumsan egestas neque in placerat sed dictum purus
													non sollicitudin consectetur. Quisque laoreet dolor nec est
													pellentesque, sed gravida ligula com modo suspendisse
													tempus sit amet nisi id aliquet.</p>
												<hr>
													<span> John Doer - <a href="#">Envato.com</a>

													</span></li>
										</div>
										<div style="width: 1100px;" class="owl-item">
											<li class="testi-slide testi_img"><a><img
													src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/testi-img.png"
													alt=""></a>
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
													Vivamus accumsan egestas neque in placerat sed dictum purus
													non sollicitudin consectetur. Quisque laoreet dolor nec est
													pellentesque, sed gravida ligula com modo suspendisse
													tempus sit amet nisi id aliquet.</p>
												<hr>
													<span> John Doer - <a href="#">Envato.com</a>

													</span></li>
										</div>
									</div>
								</div>


								<div class="owl-controls">
									<div class="owl-pagination">
										<div class="owl-page active">
											<span class=""></span>
										</div>
										<div class="owl-page">
											<span class=""></span>
										</div>
										<div class="owl-page">
											<span class=""></span>
										</div>
									</div>
								</div>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>

	<div class="clearfix"></div>
	</section> <section class=" general-row">
	<div class="wpb_column ">
		<section id="pricing">
		<div class="container">
			<span class="section-title">Tickets</span>
			<h2>Reserve Your Spot</h2>
			<hr>
				<p class="main-text center-block">Quisque cursus in augue eget
					faucibus suspendisse vel mattis libero aliquam ultricies magna nec
					nisi laoreet, sed cursus quam blandit duis.</p>
				<div class="row">
					<div
						style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
						class="col-md-4 table-item wow fadeIn" data-wow-duration="1s"
						data-wow-delay=".3s">
						<div class="wrapper">

							<h3 class="text-uppercase">Standard</h3>

							<div class="price-box">
								<sup>$</sup>29
							</div>
							<hr>

								<span class="darker">Lorem ipsum dolor sit amet</span>

								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
									Fusce lacinia eu metus ut facilisis consequat viverra.</p>

								<a href="#" class="button">Buy Ticket</a>
						
						</div>
					</div>
					<div
						style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
						class="col-md-4 table-item wow fadeIn" data-wow-duration="1s"
						data-wow-delay=".3s">
						<div class="wrapper">

							<h3 class="text-uppercase">Silver</h3>

							<div class="price-box">
								<sup>$</sup>49
							</div>
							<hr>

								<span class="darker">Lorem ipsum dolor sit amet</span>

								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
									Fusce lacinia eu metus ut facilisis consequat viverra.</p>

								<a href="#" class="button">Buy Ticket</a>
						
						</div>
					</div>
					<div
						style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
						class="col-md-4 table-item wow fadeIn" data-wow-duration="1s"
						data-wow-delay=".3s">
						<div class="wrapper">

							<h3 class="text-uppercase">Golden</h3>

							<div class="price-box">
								<sup>$</sup>99
							</div>
							<hr>

								<span class="darker">Lorem ipsum dolor sit amet</span>

								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
									Fusce lacinia eu metus ut facilisis consequat viverra.</p>

								<a href="#" class="button">Buy Ticket</a>
						
						</div>
					</div>
				</div>
		
		</div>
		</section>

	</div>

	<div class="clearfix"></div>
	</section> <section class=" margin_top">
	<div class="container">
		<div class="row">
			<div class="wpb_column col-md-6">
				<section id="faqs" class="faqs_padding"> <span class="section-title">FAQs</span>
				<h2>You Have Any question?</h2>
				<hr>
					<p class="main-text">Quisque cursus in augue eget faucibus
						suspendisse vel mattis libero aliquam ultricies magna nec.</p>
				
				</section>

				<div class="wpb_accordion wpb_content_element  not-column-inherit"
					data-collapsible="yes" data-vc-disable-keydown="false"
					data-active-tab="false">
					<div role="tablist"
						class="wpb_wrapper wpb_accordion_wrapper ui-accordion ui-widget ui-helper-reset">

						<div class="wpb_accordion_section group">
							<h3 tabindex="0" aria-expanded="false" aria-selected="false"
								aria-controls="ui-id-2" id="ui-id-1" role="tab"
								class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons">
								<span
									class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><a
									href="#section-1">Section 1</a>
							</h3>
							<div aria-hidden="true" role="tabpanel" aria-labelledby="ui-id-1"
								id="ui-id-2" style="display: none;"
								class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom">

								<div class="wpb_text_column wpb_content_element ">
									<div class="wpb_wrapper">
										<p>Sed magna velit, posuere vel scelerisque sed, fermentum sed
											ipsum. Duis tortor sem, porttitor vitae sem nec, lacinia
											placerat est. Nulla molestie eget enim a scelerisque. In
											elementum diam velit, faucibus lobortis purus scelerisque a.
											Quisque non com modo nunc. Praesent in dignissim sapien.</p>

									</div>
								</div>
							</div>
						</div>

						<div class="wpb_accordion_section group">
							<h3 tabindex="-1" aria-expanded="false" aria-selected="false"
								aria-controls="ui-id-4" id="ui-id-3" role="tab"
								class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons">
								<span
									class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><a
									href="#section-2">Section 2</a>
							</h3>
							<div aria-hidden="true" role="tabpanel" aria-labelledby="ui-id-3"
								id="ui-id-4" style="display: none;"
								class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom">

								<div class="wpb_text_column wpb_content_element ">
									<div class="wpb_wrapper">
										<p>Sed magna velit, posuere vel scelerisque sed, fermentum sed
											ipsum. Duis tortor sem, porttitor vitae sem nec, lacinia
											placerat est. Nulla molestie eget enim a scelerisque. In
											elementum diam velit, faucibus lobortis purus scelerisque a.
											Quisque non com modo nunc. Praesent in dignissim sapien.</p>

									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
			<div class="wpb_column col-md-6">

				<div class="wpb_accordion wpb_content_element  not-column-inherit"
					data-collapsible="yes" data-vc-disable-keydown="false"
					data-active-tab="false">
					<div role="tablist"
						class="wpb_wrapper wpb_accordion_wrapper ui-accordion ui-widget ui-helper-reset">

						<div class="wpb_accordion_section group">
							<h3 tabindex="0" aria-expanded="false" aria-selected="false"
								aria-controls="ui-id-6" id="ui-id-5" role="tab"
								class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons">
								<span
									class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><a
									href="#image-gallery">Image Gallery</a>
							</h3>
							<div aria-hidden="true" role="tabpanel" aria-labelledby="ui-id-5"
								id="ui-id-6" style="display: none;"
								class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom">

								<div class="wpb_gallery wpb_content_element vc_clearfix">
									<div class="wpb_wrapper">
										<div class="wpb_gallery_slides wpb_slider_nivo theme-default"
											data-interval="3">
											<div class="nivoSlider">
												<img style="display: none; width: 100px;" class=""
													src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/main-bg-250x200.jpg"
													alt="main-bg" title="main-bg" height="200" width="250"><img
													style="display: inline; width: 100px; height: auto;"
													src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/main-bg-250x200.jpg"
													class="nivo-main-image"><div style="display: block;"
															class="nivo-caption">main-bg</div>
														<div class="nivo-directionNav">
															<a class="nivo-prevNav">Prev</a><a class="nivo-nextNav">Next</a>
														</div>
											
											</div>
											<div class="nivo-controlNav">
												<a class="nivo-control active" rel="0">1</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="wpb_accordion_section group">
							<h3 tabindex="-1" aria-expanded="false" aria-selected="false"
								aria-controls="ui-id-8" id="ui-id-7" role="tab"
								class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons">
								<span
									class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><a
									href="#soundcloud">SoundCloud</a>
							</h3>
							<div aria-hidden="true" role="tabpanel" aria-labelledby="ui-id-7"
								id="ui-id-8" style="display: none;"
								class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom">

								<div class="wpb_text_column wpb_content_element ">
									<div class="wpb_wrapper">
										<p>
											<iframe
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/a.htm"
												scrolling="no" frameborder="no" height="166" width="100%"></iframe>
										</p>

									</div>
								</div>
							</div>
						</div>

						<div class="wpb_accordion_section group">
							<h3 tabindex="-1" aria-expanded="false" aria-selected="false"
								aria-controls="ui-id-10" id="ui-id-9" role="tab"
								class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons">
								<span
									class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><a
									href="#single-image">Single Image</a>
							</h3>
							<div aria-hidden="true" role="tabpanel" aria-labelledby="ui-id-9"
								id="ui-id-10" style="display: none;"
								class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom">

								<div
									class="wpb_single_image wpb_content_element wpb_animate_when_almost_visible wpb_bottom-to-top vc_align_center wpb_start_animation">
									<div class="wpb_wrapper">

										<div
											class="vc_single_image-wrapper vc_box_rounded  vc_box_border_grey"></div>
									</div>
								</div>
							</div>
						</div>

						<div class="wpb_accordion_section group">
							<h3 tabindex="-1" aria-expanded="false" aria-selected="false"
								aria-controls="ui-id-12" id="ui-id-11" role="tab"
								class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons">
								<span
									class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><a
									href="#google-map">Google Map</a>
							</h3>
							<div aria-hidden="true" role="tabpanel"
								aria-labelledby="ui-id-11" id="ui-id-12" style="display: none;"
								class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom">
								<div class="wpb_gmaps_widget wpb_content_element">
									<div class="wpb_wrapper">
										<div class="wpb_map_wraper">
											<iframe
												src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/embed.htm"
												style="border:0" frameborder="0" height="200" width="600"></iframe>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>

		</div>
	</div>
	<div class="clearfix"></div>
	</section> <section class=" general-row">
	<div class="wpb_column ">
		<section id="partners">
		<div class="container">

			<span class="section-title">Our Sponsors</span>
			<h2>Who Make it Possible</h2>
			<div class="first-row">
				<div class="item pull-left">
					<a href="#"> <img
						style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
						src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/logo6.png"
						class="wow bounceIn" data-wow-duration="1s" data-wow-delay=".3s"
						alt=""></a>
				</div>


				<div class="item pull-left">
					<a href="#"> <img
						style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
						src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/logo5.png"
						class="wow bounceIn" data-wow-duration="1s" data-wow-delay=".3s"
						alt=""></a>
				</div>


				<div class="item pull-left">
					<a href="#"> <img
						style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
						src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/logo4.png"
						class="wow bounceIn" data-wow-duration="1s" data-wow-delay=".3s"
						alt=""></a>
				</div>


			</div>
			<hr>
				<div class="second-row">

					<div class="item pull-left">
						<a href="#"> <img
							style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
							src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/logo3.png"
							class="wow bounceIn" data-wow-duration="1s" data-wow-delay=".3s"
							alt=""></a>
					</div>


					<div class="item pull-left">
						<a href="#"> <img
							style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
							src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/logo2.png"
							class="wow bounceIn" data-wow-duration="1s" data-wow-delay=".3s"
							alt=""></a>
					</div>


					<div class="item pull-left">
						<a href="#"> <img
							style="visibility: hidden; animation-duration: 1s; animation-delay: 0.3s; animation-name: none;"
							src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/logo1.png"
							class="wow bounceIn" data-wow-duration="1s" data-wow-delay=".3s"
							alt=""></a>
					</div>


				</div>
				<a href="#" class="button center-block">Sponsor us</a>
		
		</div>
		</section>

	</div>

	<div class="clearfix"></div>
	</section> </section>


	<section id="sec_49"
		style="padding:0px !important; margin:0px !important;">

	<h2 style="display: none">empty</h2>

	<section class=" general-row">
	<div class="wpb_column ">
		<section
			style="background: url('http://www.thematicwebs.com/demo/wp/eventix/layout1/wp-content/uploads/2015/07/cta-bg.jpg') no-repeat fixed center bottom;"
			id="cta-section" class="parallax-scroll5">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
					<i class="fa fa-key"></i>
					<h2>Impressed By Now?</h2>
					<p class="title">Lorem ipsum dolor set amet pelentes sentetum
						notaru</p>
					<p class="main-text">Aenean ac dignissim augue quis pharetra lorem
						vestibulum pulvinar auctor massa eu ornare vestibulum ante ipsum
						primis in faucibus orci luctus et ultrices posuere roja esciches
						cubilia curae leo.</p>

					<img
						src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/2dots.png"
						alt=""> <a href="#">register here</a> <img
						src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/4dots.png"
						alt="">
				
				</div>
			</div>
		</div>
		</section>

	</div>

	<div class="clearfix"></div>
	</section> <section class=" general-row">
	<div class="wpb_column ">
		<div id="form-section">
			<div class="container">
				<div class="row">
					<div class="col-md-12">

						<!-- Form by MailChimp for WordPress plugin v2.2.9 - https://mc4wp.com/ -->
						<div id="mc4wp-form-1" class="form mc4wp-form">
							<form lpformnum="14" method="post">
								<div class="row">
									<div class="col-md-3 col-sm-3 form-group">
										<label class="sr-only" for="input1">Name</label> <input
											class="form-control" id="input1" required=""
											placeholder="Name" name="NAME" type="text">
									
									</div>
									<div class="col-md-3 col-sm-3 form-group">
										<label class="sr-only" for="input2">Email</label> <input
											name="EMAIL" class="form-control" id="input2" required=""
											placeholder="Email" type="email">
									
									</div>
									<div class="col-md-3 col-sm-3 form-group">
										<label class="sr-only" for="input1">Telephone</label> <input
											class="form-control" id="input3" required=""
											placeholder="Telephone" name="TELEPHONE" type="tel">
									
									</div>
									<div class="col-md-3 col-sm-3 form-group">
										<button type="submit" class="gradient button">register</button>
									</div>
								</div>
								<input style="display: none;"
									name="_mc4wp_required_but_not_really" value="" type="hidden"><input
									name="_mc4wp_timestamp" value="1443491355" type="hidden"><input
										name="_mc4wp_form_submit" value="1" type="hidden"><input
											name="_mc4wp_form_instance" value="1" type="hidden"><input
												name="_mc4wp_form_nonce" value="719db1a3a5" type="hidden">
							
							</form>
						</div>
						<!-- / MailChimp for WP Plugin -->
					</div>
				</div>
			</div>
		</div>

	</div>

	<div class="clearfix"></div>
	</section> </section>

	<section id="socials">
	<div class="container container-xs-height">
		<div class="row row-xs-height">

			<div
				class="eventix_footer_widgets col-md-4 col-xs-heigh col-item tw_eventix_info-2">
				<h3>About The Event</h3>
				<p>Maecenas mollis euismod felis id auctor duis sodales sem nec
					condimentum euis mod vet tortor tortor blandit .</p>
				<a href="#" class="link">Read More</a>

			</div>
			<div
				class="eventix_footer_widgets col-md-4 col-xs-heigh col-item tw_eventix_icons-2">
				<h3>Stay In touch</h3>
				<p>Fommow us on any social media to stay tunednec condimentum euis
					mod</p>
				<ul class="socials">
					<li><a href="#"><i class="fa fa-facebook"></i></a></li>
					<li><a href="#"><i class="fa fa-youtube"></i></a></li>
					<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter"></i></a></li>
				</ul>

			</div>
			<div
				class="eventix_footer_widgets col-md-4 col-xs-heigh col-item tw_eventix_info-3">
				<h3>Event Program</h3>
				<p>Get the event program to tetur radipiscing elit ut vehicula
					lectus nunc eu vulputate dolor amet molly rino</p>
				<a href="#" class="link">Download .Pdf</a>

			</div>
		</div>
	</div>
	</section>
	<div
		style="position: relative; background-color: rgb(229, 227, 223); overflow: hidden;"
		id="map-location">
		<div class="gm-style"
			style="position: absolute; left: 0px; top: 0px; overflow: hidden; width: 100%; height: 100%; z-index: 0;">
			<div
				style="position: absolute; left: 0px; top: 0px; overflow: hidden; width: 100%; height: 100%; z-index: 0; cursor: url(&quot;https://maps.gstatic.com/mapfiles/openhand_8_8.cur&quot;), default;">
				<div
					style="position: absolute; left: 0px; top: 0px; z-index: 1; width: 100%;">
					<div
						style="position: absolute; left: 0px; top: 0px; z-index: 100; width: 100%;">
						<div style="position: absolute; left: 0px; top: 0px; z-index: 0;">
							<div aria-hidden="true"
								style="position: absolute; left: 0px; top: 0px; z-index: 1; visibility: inherit;">
								<div
									style="width: 256px; height: 256px; position: absolute; left: 626px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 626px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 882px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 882px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 370px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 370px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 626px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 626px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 882px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 882px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 1138px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 1138px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 370px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 370px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 1138px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 1138px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 114px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 114px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 114px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: 114px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: -142px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: -142px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: -142px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; position: absolute; left: -142px; top: 616px;"></div>
							</div>
						</div>
					</div>
					<div
						style="position: absolute; left: 0px; top: 0px; z-index: 101; width: 100%;"></div>
					<div
						style="position: absolute; left: 0px; top: 0px; z-index: 102; width: 100%;"></div>
					<div
						style="position: absolute; left: 0px; top: 0px; z-index: 103; width: 100%;">
						<div style="position: absolute; left: 0px; top: 0px; z-index: -1;">
							<div aria-hidden="true"
								style="position: absolute; left: 0px; top: 0px; z-index: 1; visibility: inherit;">
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 626px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 626px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 882px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 882px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 370px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 370px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 626px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 626px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 882px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 882px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 1138px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 1138px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 370px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 370px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 1138px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 1138px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 114px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 114px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 114px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 114px; top: 616px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: -142px; top: 104px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: -142px; top: 360px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: -142px; top: -152px;"></div>
								<div
									style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: -142px; top: 616px;"></div>
							</div>
						</div>
					</div>
					<div style="position: absolute; left: 0px; top: 0px; z-index: 0;">
						<div aria-hidden="true"
							style="position: absolute; left: 0px; top: 0px; z-index: 1; visibility: inherit;">
							<div
								style="position: absolute; left: 626px; top: 104px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_016.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 626px; top: 360px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_019.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 626px; top: -152px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_013.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 626px; top: 616px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_014.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 1138px; top: 104px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_021.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 1138px; top: -152px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_015.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 1138px; top: 360px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_022.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 1138px; top: 616px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_023.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 882px; top: 104px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_002.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 882px; top: 360px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_007.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 370px; top: 104px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_011.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 370px; top: 360px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_009.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 882px; top: -152px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 882px; top: 616px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_006.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 370px; top: -152px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_005.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 114px; top: 104px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_017.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 370px; top: 616px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_012.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 114px; top: 360px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_020.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 114px; top: -152px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_024.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: -142px; top: 104px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_008.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: 114px; top: 616px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_018.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: -142px; top: 360px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_010.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: -142px; top: 616px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_004.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
							<div
								style="position: absolute; left: -142px; top: -152px; transition: opacity 200ms ease-out 0s;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/vt_003.png"
									style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
						</div>
					</div>
				</div>
				<div
					style="position: absolute; left: 0px; top: 0px; z-index: 2; width: 100%; height: 100%;"></div>
				<div
					style="position: absolute; left: 0px; top: 0px; z-index: 3; width: 100%;">
					<div
						style="position: absolute; left: 0px; top: 0px; z-index: 104; width: 100%;"></div>
					<div
						style="position: absolute; left: 0px; top: 0px; z-index: 105; width: 100%;"></div>
					<div
						style="position: absolute; left: 0px; top: 0px; z-index: 106; width: 100%;"></div>
					<div
						style="position: absolute; left: 0px; top: 0px; z-index: 107; width: 100%;">
						<div
							style="cursor: default; position: absolute; width: 253px; height: 187px; left: 825px; top: 109px; z-index: 109;">
							<div style="position: absolute; left: 0px; top: 0px;">
								<div
									style="width: 0px; height: 0px; border-right: 10px solid transparent; border-left: 10px solid transparent; border-top: 24px solid rgba(0, 0, 0, 0.1); position: absolute; left: 117px; top: 187px;"></div>
								<div
									style="position: absolute; left: 0px; top: 0px; background-color: rgba(0, 0, 0, 0.2); border-radius: 2px; box-shadow: 0px 1px 4px -1px rgba(0, 0, 0, 0.3); width: 253px; height: 187px;"></div>
								<div
									style="border-top-width: 24px; position: absolute; left: 117px; top: 184px;">
									<div
										style="position: absolute; overflow: hidden; left: -6px; top: -1px; width: 16px; height: 30px;">
										<div
											style="position: absolute; left: 6px; background-color: rgb(255, 255, 255); transform: skewX(22.6deg); transform-origin: 0px 0px 0px; height: 24px; width: 10px; box-shadow: 0px 1px 6px rgba(0, 0, 0, 0.6);"></div>
									</div>
									<div
										style="position: absolute; overflow: hidden; top: -1px; left: 10px; width: 16px; height: 30px;">
										<div
											style="position: absolute; left: 0px; background-color: rgb(255, 255, 255); transform: skewX(-22.6deg); transform-origin: 10px 0px 0px; height: 24px; width: 10px; box-shadow: 0px 1px 6px rgba(0, 0, 0, 0.6);"></div>
									</div>
								</div>
								<div
									style="position: absolute; left: 1px; top: 1px; border-radius: 2px; background-color: rgb(255, 255, 255); width: 251px; height: 185px;"></div>
							</div>
							<div class="gm-style-iw"
								style="top: 9px; position: absolute; left: 15px; width: 223px;">
								<div
									style="display: inline-block; overflow: auto; max-height: 598px; max-width: 240px;">
									<div style="overflow: auto;">
										<div class="info-window">
											<h3>Location</h3>
											<span>Where you can find us</span>
											<p>ThematicWebs Team</p>
										</div>
									</div>
								</div>
							</div>
							<div
								style="width: 13px; height: 13px; overflow: hidden; position: absolute; opacity: 0.7; right: 12px; top: 10px; z-index: 10000; cursor: pointer;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/mapcnt6.png"
									style="position: absolute; left: -2px; top: -336px; width: 59px; height: 492px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
							
							</div>
						</div>
					</div>
				</div>
			</div>
			<div
				style="margin-left: 5px; margin-right: 5px; z-index: 1000000; position: absolute; left: 0px; bottom: 0px;">
				<a title="Click to see this area on Google Maps"
					href="https://maps.google.com/maps?ll=46.138927,-60.24765&amp;z=13&amp;t=m&amp;hl=en-US&amp;gl=US&amp;mapclient=apiv3"
					target="_blank"
					style="position: static; overflow: visible; float: none; display: inline;"><div
						style="width: 66px; height: 26px; cursor: pointer;">
						<img draggable="false"
							src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/google4.png"
							style="position: absolute; left: 0px; top: 0px; width: 66px; height: 26px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
					
					</div></a>
			</div>
			<div
				style="background-color: white; padding: 15px 21px; border: 1px solid rgb(171, 171, 171); font-family: Roboto, Arial, sans-serif; color: rgb(34, 34, 34); box-shadow: 0px 4px 16px rgba(0, 0, 0, 0.2); z-index: 10000002; display: none; width: 256px; height: 148px; position: absolute; left: 485px; top: 230px;">
				<div style="padding: 0px 0px 10px; font-size: 16px;">Map Data</div>
				<div style="font-size: 13px;">Map data ©2015 Google</div>
				<div
					style="width: 13px; height: 13px; overflow: hidden; position: absolute; opacity: 0.7; right: 12px; top: 12px; z-index: 10000; cursor: pointer;">
					<img draggable="false"
						src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/mapcnt6.png"
						style="position: absolute; left: -2px; top: -336px; width: 59px; height: 492px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
				
				</div>
			</div>
			<div
				style="z-index: 1000001; position: absolute; right: 0px; bottom: 0px; width: 12px;"
				class="gmnoprint">
				<div class="gm-style-cc"
					style="-moz-user-select: none; height: 14px; line-height: 14px;"
					draggable="false">
					<div
						style="opacity: 0.7; width: 100%; height: 100%; position: absolute;">
						<div style="width: 1px;"></div>
						<div
							style="background-color: rgb(245, 245, 245); width: auto; height: 100%; margin-left: 1px;"></div>
					</div>
					<div
						style="position: relative; padding-right: 6px; padding-left: 6px; font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); white-space: nowrap; direction: ltr; text-align: right; vertical-align: middle; display: inline-block;">
						<a
							style="color: rgb(68, 68, 68); text-decoration: none; cursor: pointer; display: none;">Map
							Data</a><span style="">Map data ©2015 Google</span>
					</div>
				</div>
			</div>
			<div style="position: absolute; right: 0px; bottom: 0px;"
				class="gmnoscreen">
				<div
					style="font-family: Roboto, Arial, sans-serif; font-size: 11px; color: rgb(68, 68, 68); direction: ltr; text-align: right; background-color: rgb(245, 245, 245);">Map
					data ©2015 Google</div>
			</div>
			<div draggable="false"
				style="z-index: 1000001; -moz-user-select: none; height: 14px; line-height: 14px; position: absolute; right: 0px; bottom: 0px;"
				class="gmnoprint gm-style-cc">
				<div
					style="opacity: 0.7; width: 100%; height: 100%; position: absolute;">
					<div style="width: 1px;"></div>
					<div
						style="background-color: rgb(245, 245, 245); width: auto; height: 100%; margin-left: 1px;"></div>
				</div>
				<div
					style="position: relative; padding-right: 6px; padding-left: 6px; font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); white-space: nowrap; direction: ltr; text-align: right; vertical-align: middle; display: inline-block;">
					<a target="_blank"
						href="https://www.google.com/intl/en-US_US/help/terms_maps.html"
						style="text-decoration: none; cursor: pointer; color: rgb(68, 68, 68);">Terms
						of Use</a>
				</div>
			</div>
			<div class="gm-style-cc"
				style="-moz-user-select: none; height: 14px; line-height: 14px; position: absolute; right: 0px; bottom: 0px;"
				draggable="false">
				<div
					style="opacity: 0.7; width: 100%; height: 100%; position: absolute;">
					<div style="width: 1px;"></div>
					<div
						style="background-color: rgb(245, 245, 245); width: auto; height: 100%; margin-left: 1px;"></div>
				</div>
				<div
					style="position: relative; padding-right: 6px; padding-left: 6px; font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); white-space: nowrap; direction: ltr; text-align: right; vertical-align: middle; display: inline-block;">
					<a
						href="https://www.google.com/maps/@46.138927,-60.2476497,13z/data=%2110m1%211e1%2112b1?source=apiv3&amp;rapsrc=apiv3"
						style="font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); text-decoration: none; position: relative;"
						title="Report errors in the road map or imagery to Google"
						target="_new">Report a map error</a>
				</div>
			</div>
			<div controlheight="93" controlwidth="28" draggable="false"
				style="margin: 10px; -moz-user-select: none; position: absolute; bottom: 93px; right: 28px;"
				class="gmnoprint">
				<div controlheight="55" controlwidth="28"
					style="position: absolute; left: 0px; top: 38px;" class="gmnoprint">
					<div
						style="-moz-user-select: none; box-shadow: 0px 1px 4px -1px rgba(0, 0, 0, 0.3); border-radius: 2px; cursor: pointer; background-color: rgb(255, 255, 255); width: 28px; height: 55px;"
						draggable="false">
						<div
							style="position: relative; width: 28px; height: 27px; left: 0px; top: 0px;"
							title="Zoom in">
							<div
								style="overflow: hidden; position: absolute; width: 15px; height: 15px; left: 7px; top: 6px;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/tmapctrl.png"
									style="position: absolute; left: 0px; top: 0px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px; width: 120px; height: 54px;">
							
							</div>
						</div>
						<div
							style="position: relative; overflow: hidden; width: 67%; height: 1px; left: 16%; background-color: rgb(230, 230, 230); top: 0px;"></div>
						<div
							style="position: relative; width: 28px; height: 27px; left: 0px; top: 0px;"
							title="Zoom out">
							<div
								style="overflow: hidden; position: absolute; width: 15px; height: 15px; left: 7px; top: 6px;">
								<img draggable="false"
									src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/tmapctrl.png"
									style="position: absolute; left: 0px; top: -15px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px; width: 120px; height: 54px;">
							
							</div>
						</div>
					</div>
				</div>
				<div controlheight="28" controlwidth="28"
					style="box-shadow: 0px 1px 4px -1px rgba(0, 0, 0, 0.3); border-radius: 2px; width: 28px; height: 28px; cursor: url(&quot;https://maps.gstatic.com/mapfiles/openhand_8_8.cur&quot;), default; background-color: rgb(255, 255, 255); position: absolute; left: 0px; top: 0px;">
					<div style="position: absolute; left: 1px; top: 1px;"></div>
					<div style="position: absolute; left: 1px; top: 1px;">
						<div aria-label="Street View Pegman Control"
							style="width: 26px; height: 26px; overflow: hidden; position: absolute; left: 0px; top: 0px;">
							<img draggable="false"
								src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/cb_scout5.png"
								style="position: absolute; left: -147px; top: -26px; width: 215px; height: 835px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
						
						</div>
						<div aria-label="Pegman is on top of the Map"
							style="width: 26px; height: 26px; overflow: hidden; position: absolute; left: 0px; top: 0px; visibility: hidden;">
							<img draggable="false"
								src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/cb_scout5.png"
								style="position: absolute; left: -147px; top: -52px; width: 215px; height: 835px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
						
						</div>
						<div aria-label="Street View Pegman Control"
							style="width: 26px; height: 26px; overflow: hidden; position: absolute; left: 0px; top: 0px; visibility: hidden;">
							<img draggable="false"
								src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/cb_scout5.png"
								style="position: absolute; left: -147px; top: -78px; width: 215px; height: 835px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
						
						</div>
					</div>
				</div>
				<div style="display: none; position: absolute;" controlheight="0"
					controlwidth="28" class="gmnoprint">
					<div title="Rotate map 90 degrees"
						style="width: 28px; height: 28px; overflow: hidden; position: absolute; border-radius: 2px; box-shadow: 0px 1px 4px -1px rgba(0, 0, 0, 0.3); cursor: pointer; background-color: rgb(255, 255, 255); display: none;">
						<img draggable="false"
							src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/tmapctrl4.png"
							style="position: absolute; left: -141px; top: 6px; width: 170px; height: 54px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
					
					</div>
					<div class="gm-tilt"
						style="width: 28px; height: 28px; overflow: hidden; position: absolute; border-radius: 2px; box-shadow: 0px 1px 4px -1px rgba(0, 0, 0, 0.3); top: 0px; cursor: pointer; background-color: rgb(255, 255, 255);">
						<img draggable="false"
							src="Eventix%20%E2%80%93%20Layout1%20%E2%80%93%20Demo_files/tmapctrl4.png"
							style="position: absolute; left: -141px; top: -13px; width: 170px; height: 54px; -moz-user-select: none; border: 0px none; padding: 0px; margin: 0px;">
					
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
				jQuery(document).ready(function($) {
				
					function initialize() {
							
							var windowLatLng = new google.maps.LatLng(46.138927, -60.193233);
							
							var mapCanvas = document.getElementById('map-location');
							
							var mapOptions = {
								center: windowLatLng,
								zoom: 13,
								scrollwheel: false,
								navigationControl: false,
								mapTypeControl: false,
								scaleControl: false,
								mapTypeId: google.maps.MapTypeId.ROADMAP
							}
							
							var map = new google.maps.Map(mapCanvas, mapOptions);
							
							var contentString = '<div class="info-window">'+
								'<h3>Location</h3>'+
								'<span>Where you can find us</span>'+
								'<p>ThematicWebs Team</p>'+
								'</div>';
						
							var infowindow = new google.maps.InfoWindow({
								content: contentString,
								maxWidth: 240
							});
							
							var marker = new google.maps.Marker({
								position: windowLatLng,
								map: map,
								title: 'Hello World!',
								show: true
							});
							
							google.maps.event.addListener(marker, 'click', function() {
								infowindow.open(map, marker);
							});
							
							google.maps.event.trigger(marker, 'click')
							
							marker.setVisible(false)
							
						  }
						  google.maps.event.addDomListener(window, 'load', initialize);
					});
				</script>
	<footer>
	<div class="container">
		<div class="row">
			<div class="col-sm-5">
				<p class="copyright">©2015 Eventix, All Rights Reserved</p>
			</div>
			<div class="col-sm-7">
				<ul class="list-inline pull-right">
					<li><a href="#">Affiliates</a></li>
					<li><a href="#">Contact</a></li>
					<li><a href="#">Privacy</a></li>
					<li><a href="#">Terms of Use</a></li>
				</ul>
			</div>
		</div>
	</div>
	</footer>

	<script type="text/javascript">
			(function() {

				function addSubmittedClass() {
					var className = 'mc4wp-form-submitted';
					(this.classList) ? this.classList.add(className) : this.className += ' ' + className;
				}

				var forms = document.querySelectorAll('.mc4wp-form');
				for (var i = 0; i < forms.length; i++) {
					(function(f) {

						// hide honeypot
						var honeypot = f.querySelector('input[name="_mc4wp_required_but_not_really"]');
						honeypot.style.display = 'none';
						honeypot.setAttribute('type','hidden');

						// add class on submit
						var b = f.querySelector('[type="submit"]');
						if(b.addEventListener) {
							b.addEventListener( 'click', addSubmittedClass.bind(f));
						} else {
							b.attachEvent( 'onclick', addSubmittedClass.bind(f));
						}

					})(forms[i]);
				}
			})();

					</script>
</body>
</html>
