<?php 
/**
 * @author		Sashas
 * @category    Sashas
 * @package     Sashas_QandA
 * @copyright   Copyright (c) 2015 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0 GNU License, version 3 (GPL-3.0)
 */
?> 
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Product Questions') ?></h1>
</div>
 <?php if( $this->getCollection() && $this->count()): ?>
    <?php echo $this->getToolbarHtml() ?>
        <table class="data-table" id="my-questions-table">
            <col width="1" />
            <col width="210" />           
            <col />            
            <tbody>
                <?php foreach ($this->getCollection() as $_question): ?>
                <tr>
                    <td><span class="nobr"><?php echo $this->dateFormat($_question->getCreatedAt()); ?></span></td>
                    <td><h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_question->getProductId() ?>"><?php echo $this->htmlEscape($_question->getQuestion()) ?></a></h2></td>
 					<?php if ($_question->getAnswer() && $_question->getStatus()==1):?>
                    	<td><?php echo $this->htmlEscape($_question->getAnswer()) ?></td>
                    <?php else:?>
                    	<td><?php echo $this->__('Question is not answered yet'); ?></td>
                    <?php endif;?>                    
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>    
        <script type="text/javascript">decorateTable('my-questions-table')</script>
    <?php echo $this->getToolbarHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You have submitted no questions.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>    
 
