<?php
/**
 * @author		Sashas
 * @category    Sashas
 * @package     Sashas_Extensions
 * @copyright   Copyright (c) 2016 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<?php if ($this->getTotals()): ?>
<tfoot>
    <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
    <tr>
        <td class="a-right" colspan="<?php echo $_colspan; ?>">
            <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
        </td>
        <td class="a-right">
            <small><?php echo $this->displayBaseGrandtotal() ?></small>
        </td>
    </tr>
    <?php endif?>
</tfoot>
<?php endif; ?>
