<?php
/**
 * @author		Sashas
 * @category    Sashas
 * @package     Sashas_Extensions
 * @copyright   Copyright (c) 2016 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<?php
    $methods = $this->getMethods();
    $oneMethod = count($methods) <= 1;
?>
<form id="co-payment-form" action="">
	<?php if (empty($methods)): ?>
	    <dt>
	        <?php echo $this->__('No Payment Methods') ?>
	    </dt>
	<?php else:
	    foreach ($methods as $_method):
	        $_code = $_method->getCode();
	?>
	    <dt id="dt_method_<?php echo $_code ?>">
	    <?php if(!$oneMethod): ?>
	        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>"  <?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
	    <?php else: ?>
	        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
	        <?php $oneMethod = $_code; ?>
	    <?php endif; ?>
	        <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
	    </dt>
	    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
	    <dd id="dd_method_<?php echo $_code ?>">
	        <?php echo $html; ?>
	    </dd>
	    <?php endif; ?>
	<?php endforeach;
	    endif;
	?>
	<?php echo $this->getChildChildHtml('additional'); ?>
	<script type="text/javascript">
	    //<![CDATA[
	    <?php echo $this->getChildChildHtml('scripts'); ?>   
	    //]]>
	</script>
</form>
<div class="paypal_info">	 
	<div id="checkout-paypaliframe-load" class="authentication"></div> 
</div>