<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */

/* @var $this Mage_Catalog_Block_Product_View_Media */
?>
<?php

$_product = $this->getProduct ();
$_helper = $this->helper ( 'catalog/output' );
?>
<div class="product-image product-image-zoom">
	<div class="product-image-gallery">
		<img id="image-main" class="gallery-image visible"   
			src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
			alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
			title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
	</div>
</div>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
	<h2><?php echo $this->__('More Views') ?></h2>
	<ul class="product-image-thumbs" id="gallery">
    <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
        <?php
		if (($filterClass = $this->getGalleryFilterHelper ()) && ($filterMethod = $this->getGalleryFilterMethod ()) && ! Mage::helper ( $filterClass )->$filterMethod ( $_product, $_image )) :
			continue;
		
		
        endif;
		?>
        <li><a class="product-thumb fancybox" rel="gallery1"
			title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"
			href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(false)->constrainOnly(true); ?>">
				<img
				src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(75); ?>" />

		</a></li>         
    <?php $i++; endforeach; ?>
    
    </ul>
</div>
<script type="text/javascript">
<!--
jQuery(document).ready(function() {
	jQuery(".fancybox").fancybox({
		openEffect	: 'none',
		closeEffect	: 'none'
	});
});
//-->
</script>
<?php endif; ?>

 
<?php echo $this->getChildHtml('after'); ?>
