<?php if($this->getItems()->getSize()): ?>
<div class="block block-related">
    <div class="block-title">
        <h2><?php echo $this->__('You may also be interested in') ?></h2>
    </div>
    <div class="block-content">        
        <ol class="mini-products-list" id="block-related">
        <?php $i=0;?>
        <?php foreach($this->getItems() as $_item): ?>
            <li class="item"> 
                <div class="product">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(210) ?>"  alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></p>
                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
        <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
    </div> 
</div>
<?php endif ?>
