<?php
/* @var $this Strongtics_RichSnippets_Block_Page_Html_Breadcrumbs */
?>
<?php
if (!$crumbs || !is_array($crumbs)):
    return;
endif;
?>

<div class="breadcrumbs">
    <ul>
        <?php foreach ($crumbs as $_crumbName => $_crumbInfo) : ?>
            <li class="<?php echo $_crumbName ?>" itemscope="itemscope" itemtype="http://data-vocabulary.org/Breadcrumb">
                <?php if ('home' == $_crumbName) : ?>
                    <a title="<?php echo $_crumbInfo['label']; ?>" href="<?php echo $_crumbInfo['link']; ?>" itemprop="url"><span itemprop="title"><?php echo $this->escapeHtml($_crumbInfo['label']); ?></span></a>
                <?php elseif ($_crumbInfo['last']) : ?>
		    <a href="#" title="<?php echo $this->escapeHtml($_crumbInfo['label']); ?>" itemprop="url"><span itemprop="title"><?php echo $_crumbInfo['label']; ?></span></a>
                <?php elseif ($_crumbInfo['link']) : ?>
                    <a href="<?php echo $_crumbInfo['link']; ?>" title="<?php echo $this->escapeHtml($_crumbInfo['label']); ?>" itemprop="url"><span itemprop="title"><?php echo $_crumbInfo['label']; ?></span></a>
                <?php else : ?>
                    <?php echo $_crumbInfo['label']; ?>
                <?php endif; ?>
                <?php if (!$_crumbInfo['last']) : ?>
                    <span>> </span>
                <?php endif ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
