<div class="product-img-box">
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom">
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image');?>"  data-lightbox="product-image" title="<?php echo $this->escapeHtml($this->getImageLabel()) ?>">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    </a> 
</p>
<p class="zoom-notice" id="track_hint"><?php echo $this->__('Click on image to view full picture') ?></p>
 
<?php else: ?>
<p class="product-image">
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image');?>"  data-lightbox="product-image" title="<?php echo $this->escapeHtml($this->getImageLabel()) ?>">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    </a> 
</p>
<p class="zoom-notice" id="track_hint"><?php echo $this->__('Click on image to view full picture') ?></p>
 
<?php endif; ?>
</div>  
</div><?php // end class product-top-container ?>
<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>"  data-lightbox="product-image" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" /></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
