<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
 
<header id="header" class="page-header">
    <div class="page-header-container">
    	<div class="left-contanier">
	        <a class="logo" href="<?php echo $this->getUrl('') ?>">
	            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
	            <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
	        </a>
        </div>
		<div class="right-container">
 			
	        <!-- Search -->
	        <div id="header-search" class="skip-content">
	            <?php echo $this->getChildHtml('topSearch') ?>
	        </div> 		    
	        		
	        <?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
	              // See app.js for details ?>
	        <div class="store-language-container"><?php echo $this->getChildHtml('store_language') ?></div>	
	        <!-- Skip Links -->
	        <div class="skip-links">
	            <a href="#header-nav" class="skip-link skip-nav">
	                <span class="icon"></span>
	                <span class="label"><?php echo $this->__('Menu'); ?></span>
	            </a>
	            <a href="#header-search" class="skip-link skip-search">
	                <span class="icon"></span>
	                <span class="label"><?php echo $this->__('Search'); ?></span>
	            </a>
	            <div class="account-cart-wrapper">            
	                <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account">
	                    <span class="icon"></span>
	                    <span class="label"><?php echo $this->__('Account'); ?></span>
	                </a>
	                <!-- Cart -->
	                <div class="header-minicart">
	                    <?php echo $this->getChildHtml('minicart_head'); ?>
	                </div>
	            </div>
	        </div>
	        <!-- Account -->
	        <div id="header-account" class="skip-content">
	            <?php echo $this->getChildHtml('topLinks') ?>
	        </div>		        
         
 
 	
		</div>		 
    </div>
 	<!-- Navigation -->
    <div id="header-nav" class="skip-content">
		<?php echo $this->getChildHtml('topMenu') ?>
	</div>    
</header>


<?php echo $this->getChildHtml('topContainer'); ?>
