<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<header id="header" class="page-header">
    <nav class="navbar main-navigation-header navbar-fixed-top sticky-navbar">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="<?php echo Mage::getBaseUrl();?>" class="navbar-brand logo">
                    <img src="<?php echo $this->getSkinUrl('images/aboutus/logo_white.png'); ?>" alt="" >
                </a>
            </div>
            <div class="collapse navbar-collapse" id="header-navigation">
                <div class="account-cart-wrapper">
                    <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account"><span class="icon"></span></a>
                    <div class="header-minicart">
                        <?php echo $this->getChildHtml('minicart_head'); ?>
                    </div>
                    <a href="javascript:void(0)"  class="skip-link top-search-icon"><span class="icon"></span></a>
                    <div id="header-account" class="skip-content">
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </div>
                </div>
                <?php echo $this->getChildHtml('topMenu') ?>
            </div>
            <div class="store-language-container"><?php echo $this->getChildHtml('store_language') ?></div>
        </div><!-- /.container-fluid -->
        <div class="container">
            <div id="header-search" class="skip-content">
                <?php echo $this->getChildHtml('topSearch') ?>
            </div>
        </div>
    </nav>
</header>
<?php echo $this->getChildHtml('topContainer'); ?>
<script type="application/javascript">
    jQuery( document ).ready(function() {
        jQuery('.top-search-icon').click(function(){
            jQuery( "#header-search" ).slideToggle();
        });
    });
</script>