<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top') ?>

<?php if($_menu): ?>
    <nav id="nav">
        <ol class="nav-primary nav navbar-nav main-navigation navbar-right">
            <?php echo $_menu ?>
            <?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('after_menu')->toHtml(); ?>       
        </ol>
    </nav>
<?php endif ?>
